marcajujuy/core/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'corejujuy'
urlpatterns = [
    url(r'^$', views.home, name='home'),

    url('^consultas/$', views.mostrar_consultas, name='mostrar_consultas'),
    path('responder/<int:consulta_id>/', views.responder_consulta, name='responder_consulta'),
]

marcajujuy/marcajujuy/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings',)),
    url(r'^tinymce/', include('tinymce.urls')),
    
    #Proyectos Propios
    path('', include('core.urls')),
    path('', include('registro.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('fotos/', include('fotos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marcajujuy/core/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import *
from django.contrib.auth.models import User
from marcajujuy.settings import MEDIA_URL
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating
from tinymce.models import HTMLField

#Create your models here.
class Archivo(models.Model):
    nombre = models.CharField('Titulo', max_length=200)
    descripcion = HTMLField()
    captura = models.ImageField(storage=FileSystemStorage(location=MEDIA_URL), null=True)
    archivo = models.FileField(upload_to='')
    pub_date = models.DateTimeField('Fecha de Publicacion', default=datetime.datetime.now)
    ratings = GenericRelation(Rating, related_query_name='archivos')
    def __str__(self):
        return self.nombre

#Comentarios
class Comentario(models.Model):
    archivo = models.ForeignKey(Archivo, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    comentario = models.TextField()
    def __str__(self):
        return self.archivo.nombre + '-' + self.usuario.username

#Elementos del FAQ
class Faq(models.Model):
    orden = models.IntegerField()
    pregunta = models.CharField('Titulo', max_length=200)
    respuesta = HTMLField()
    def __str__(self):
        return self.pregunta

#Consulta
class Consulta(models.Model):
    email = models.EmailField()
    nombre = models.CharField('Titulo', max_length=20)
    mensaje = models.TextField()
    respondida = models.BooleanField(default=False)
    def __str__(self):
        return self.email + '-' + self.mensaje

#Respuestas
class Respuesta(models.Model):
    consulta = models.ForeignKey(Consulta, on_delete=models.DO_NOTHING)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    respuesta = models.TextField()
    def __str__(self):
        return self.usuario.username + '-' + self.respuesta

marcajujuy/core/forms.py
from django import forms

class ContactoForm(forms.Form):
    email = forms.EmailField()
    nombre = forms.CharField(max_length=20, help_text='')
    mensaje = forms.CharField(widget=forms.Textarea(attrs={'width':"100%", 'cols' : "40", 'rows': "2"}))

class ResponderForm(forms.Form):
    respuesta = forms.CharField(widget=forms.Textarea(attrs={'width':"100%", 'cols' : "40", 'rows': "2"}))

marcajujuy/core/views.py
from django.http import Http404
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.admin.views.decorators import staff_member_required
from django.core.mail import EmailMessage
#Import Personales
from .models import Faq, Consulta, Respuesta
from .forms import ContactoForm, ResponderForm
from biblioteca.models import Archivo
from fotos.models import Album

#@login_required
def home(request):
    #Obtenemos los archivos que se van a mostrar:
    archivos = Archivo.objects.order_by('pub_date')[:4]
    albums = Album.objects.order_by('pub_date')[:4]
    #Analizamos si nos mandaron una consulta
    if request.method == 'POST':
        form = ContactoForm(request.POST)
        if form.is_valid():
            #Procesamos el mensaje
            consulta = Consulta()
            consulta.email = form.cleaned_data['email']
            consulta.nombre = form.cleaned_data['nombre']
            consulta.mensaje = form.cleaned_data['mensaje']
            consulta.save()
    form = ContactoForm()
    #Obtenemos los datos del FAQ
    faqs = Faq.objects.all()
    #Enviamos la pagina
    return render(request, 'home.html', {'faqs' : faqs, 'archivos': archivos, 'albums': albums, 'form' : form })

@staff_member_required
def mostrar_consultas(request):
    consultas = Consulta.objects.all()
    return render(request, 'consultas.html', {'consultas' : consultas })

@staff_member_required
def responder_consulta(request, consulta_id):
    #Obtenemos la Consulta Especifica
    consulta = Consulta.objects.get(id=consulta_id)
    #Si se respondio a la misma:
    if request.method == 'POST':
        form = ResponderForm(request.POST)
        if form.is_valid():
            respuesta = Respuesta()
            respuesta.consulta = consulta
            respuesta.usuario = User.objects.get(username=request.user.username)
            respuesta.respuesta = form.cleaned_data['respuesta']
            respuesta.save()
            consulta.respondida = True
            consulta.save()
            #Enviar Correo
            mensaje = 'Su consulta fue: ' + consulta.mensaje + '\n' + 'Nuestra Respuesta:' + respuesta.respuesta
            email = EmailMessage('Marca Jujuy - Respuesta a Su consulta.',
                       mensaje, to=[consulta.email])
            email.send()
    #Instanciamos Formulario de Respuesta
    form = ResponderForm()
    return render(request, 'responder.html', {'consulta' : consulta, 'form' : form, })

marcajujuy/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Jujuy - Energia Viva{% endblock %}</title>

    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/masonry.pkgd.min.js' %}"></script>
    
  </head>
  <body id="body">
      <nav class="navbar navbar-collapse" id="navbar">
        <div class="navbar-brand">
          <a href="/">
            <img src="{% static 'img/logo1.png' %}" />
          </a>
        </div>
        
        <ul class="nav nav-pills navbar-right">
          {% if user.is_authenticated %}
          <li class="bienvenido">Bienvenido, {{ user.get_full_name }} <small>{{ user.username }}</small>!</li>
          {% if user.is_staff %}
          <li><a href="/administracion">Admin</a></li>
          {% endif %}
          <li><a href="{% url 'logout' %}">Salir</a></li>
          {% else %}
          <li class="btn-login"><a href="{% url 'login' %}">Ingresar</a></li><li><a href="{% url 'signup' %}">Registrarse</a></li>
          {% endif %}
        </ul>
     
      </nav>
    </header>
    
    <main>
      {% block content %}
      
      {% endblock %}
    </main>
    
    {% load static %}
    <style type="text/css">
      @font-face {
        font-family: Archia;
        font-weight: normal;
        src: url({% static 'fonts/Archia-Regular.otf' %}) format('truetype');
        src: local({% static 'fonts/Archia-Regular.otf' %}) format('truetype');
     }
      @font-face {
        font-family: Archia;
        font-weight: bold;
        src: url({% static 'fonts/Archia-Bold.otf' %}) format('truetype');
        src: local({% static 'fonts/Archia-Bold.otf' %}) format('truetype');
     }
      @font-face {
        font-family: Archia;
        font-weight: lighter;
        src: url({% static 'fonts/Archia-Thin.otf' %}) format('truetype');
        src: local({% static 'fonts/Archia-Thin.otf' %}) format('truetype');
     }
    </style>
    <script type="text/javascript" src="{% static 'js/jMouseWheel.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
  </body>
</html>

marcajujuy/core/templates/consultas.html
{% extends 'base.html' %}

{% block content %}
<h3>Consultas Sin Responder</h3>
<ul>
  {% for consulta in consultas %}
    {% if not consulta.respondida %}
    <li>
            <hr>
            <h4>{{ consulta.nombre }} - {{ consulta.email }}</h4>
            <p><b>Consulta:</b> {{ consulta.mensaje }}</p>
            <a href="{% url 'corejujuy:responder_consulta' consulta.id %}"><p>Responder</p></a>
    </li>
    {% endif %}
  {% endfor %}
</ul>

<!-- Estaria buenisimo que las respondidas aparezcan en un costadito, como un historial, a la derecha mas pequeno -->
<hr>
<h3>Consultas Respondidas</h3>
<ul>
    {% for consulta in consultas %}
        {% if consulta.respondida %}
    <li>
            <hr>
            <h4>{{ consulta.nombre }} - {{ consulta.email }}</h4>
            <p><b>Consulta:</b> {{ consulta.mensaje }}</p>
            <h5><b>Respuestas enviadas:</b></h5>
            <ul>
            {% for respuesta in consulta.respuesta_set.all %}
                <li>
                    <p>{{ respuesta.respuesta }} - {{ respuesta.usuario.username }}</p>
                </li>
            {% endfor %}
            </ul>
    </li>
    <a href="{% url 'corejujuy:responder_consulta' consulta.id %}"><p>Responder</p></a>
    {% endif %}
  {% endfor %}
</ul>

{% endblock %}

marcajujuy/core/templates/home.html
{% extends 'base.html' %}

{% block content %}
<section class="home">
  <div class="paginacion">
    <a href="#body" class="active"><div class="pelotita"></div></a>
    <a href="#faq"><div class="pelotita"></div></a>
    <a href="#archivos"><div class="pelotita"></div></a>
    <a href="#fotos"><div class="pelotita"></div></a>
    <a href="#registro"><div class="pelotita"></div></a>
  </div>
  
  <section class="full-width logo-principal" id="principal">
    <div class="logo-grande">
        <div class="logo-nubes">

        </div>
        <div class="logo-nubes2">
          
        </div>
        <div class="logo-overlay">
          
        </div>
    </div>
    
    <div class="slogan">
      El mundo necesita escuchar lo que tenemos para contarle.<br>
      Precisa ver lo que tenemos para mostrarle.<br>
      Anhela experimentar lo que tenemos para ofrecerle.
    </div>
</section>
  
<section class="seccion-faq" id="faq">
  <!--Listado Preguntas y Respuestas del FAQ)-->
  <br><h1>Preguntas frecuentes</h1>
  <hr>
  <ul class="faq col-md-4">
    {% for faq in faqs %}
      <li>
          <div class="contenedor-faq">
            <a href="#"><h3>{{ faq.pregunta }}</h3></a>
            <div class="contenedor-respuesta">{{ faq.respuesta | safe }}</div>
          </div>
      </li>
    {% endfor %}
  </ul>
  <div class="col-md-8">
    <div class="respuesta-activa">
      
    </div>
  </div>
</section>

<section class="seccion-archivos full-width" id="archivos">
  <!--Listado de Archivos (Aca deberias generar los bloques irregulares)-->
  <br><h1>Archivos</h1>
  <hr>
  <div class="link-biblioteca">
    Acceda a la Biblioteca de Archivos <a href="/biblioteca/">Aqui</a>
  </div>
  <div class="lista-archivos">
    <ul class="grid">
      {% for archivo in archivos %}
        <li class="grid-item">
            <a href="/biblioteca/{{ archivo.id }}">
                <br><h2>{{ archivo.nombre }}</h2>
                <div class="img">
                  <img src="/{{ archivo.captura.url }}" alt="{{ archivo.nombre }}">
                </div>
            </a>
        </li>
      {% endfor %}
    </ul>
  </div>
</section>

<section class="seccion-fotos full-width" id="fotos">
  <!--Listado de Archivos (Aca deberias generar los bloques irregulares)-->
  <br><h1>Fotos</h1>
  <hr>
  <div class="link-biblioteca">
    Acceda a la Biblioteca de Imagenes <a href="/fotos/">Aqui</a>
  </div>
  <div class="lista-fotos">
    <ul class="grid">
      {% for album in albums %}
        <li class="grid-item">
            <a href="/fotos/{{ album.id }}">
                <br><h2>{{ album.nombre }}</h2>
                <div class="img">
                  <img src="/{{ album.portada.url }}" alt="{{ album.nombre }}">
                </div>
            </a>
        </li>
      {% endfor %}
    </ul>
  </div>
</section>

<section class="seccion-registro" id="registro">
  
    <div class="col-md-6">
      <!-- invitacion a registrarse -->
      <h3>Registro:</h3>
      <p>Si sos emprendedor jujeño registrate para acceder a los editables y las guías de aplicación</p>
      <a href="/signup/">Registrate!</a>
    </div>
    
    <div class="col-md-6">
      <!--Contacto-->
      <h3>Contacto:</h3>
      <form method="post">
        {% csrf_token %}
        <div class="input-group">
          <label for="id_email">Email:</label>
          <input type="email" name="email" id="id_email" class="form-control" required />
        </div>
        <div class="input-group">
          <label for="id_nombre">Nombre:</label>
          <input type="text" name="nombre" maxlength="20" id="id_nombre" class="form-control" required />
        </div>
        <div class="input-group">
          <label for="id_mensaje">Mensaje:</label>
          <textarea name="mensaje" required cols="40" width="100%" rows="2" id="id_mensaje" class="form-control"></textarea>
        </div>
      
        <button type="submit">Enviar Consulta</button>
      </form>
    </div>
</section>

<script>
$('.grid').masonry({
  // options
  itemSelector: '.grid-item',
  columnWidth: 580,
  gutter: 5,
  fitWidth: true
});
</script>

</section>

{% endblock %}

marcajujuy/core/templates/responder.html
{% extends 'base.html' %}

{% block content %}
    <br><h2>Consulta:</h2>
    <h3>{{ consulta.nombre }} - {{ consulta.email }}</h3>
    <p><b>Consulta:</b>{{ consulta.mensaje }}</p>
    {% if consulta.respondida %}
    <hr>
    <h3> Respuestas enviadas:</h3>
        {% for respuesta in consulta.respuesta_set.all %}
            <p>{{ respuesta.respuesta }} - {{ respuesta.usuario.username }}</p>
        {% endfor %}
    {% endif %}
    <hr>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Responder</button>
    </form>
    
{% endblock %}