marcajujuy/core/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'corejujuy'
urlpatterns = [
    url(r'^$', views.home, name='home'),

    url('^consultas/$', views.mostrar_consultas, name='mostrar_consultas'),
    path('responder/<int:consulta_id>/', views.responder_consulta, name='responder_consulta'),
]

marcajujuy/marcajujuy/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings',)),
    url(r'^tinymce/', include('tinymce.urls')),
    
    #Proyectos Propios
    path('', include('core.urls')),
    path('', include('registro.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('fotos/', include('fotos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marcajujuy/registro/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
#Import Personales
from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^administracion/$', views.administracion, name='administracion'),
    url(r'^usuarios/$', views.mostrar_usuarios, name='mostrar_usuarios'),
    path('activar/<int:user_id>/', views.activar_usuario, name='activar_usuario'),
    path('desactivar/<int:user_id>/', views.desactivar_usuario, name='desactivar_usuario'),
]

marcajujuy/registro/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    nombre = models.TextField(max_length=50, null=True)
    apellido = models.TextField(max_length=50, null=True)
    localidad = models.CharField(max_length=30, blank=True)
    telefono = models.TextField(max_length=20,null=True)
    empresa = models.TextField(max_length=100, null=True)
    producto = models.TextField(null=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

marcajujuy/core/forms.py
from django import forms

class ContactoForm(forms.Form):
    email = forms.EmailField()
    nombre = forms.CharField(max_length=20, help_text='')
    mensaje = forms.CharField(widget=forms.Textarea(attrs={'width':"100%", 'cols' : "40", 'rows': "2"}))

class ResponderForm(forms.Form):
    respuesta = forms.CharField(widget=forms.Textarea(attrs={'width':"100%", 'cols' : "40", 'rows': "2"}))

marcajujuy/registro/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    localidad = forms.CharField(max_length=30)
    telefono = forms.CharField(max_length=20)
    empresa = forms.CharField(max_length=100)
    producto = forms.CharField(widget=forms.widgets.Textarea())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

marcajujuy/registro/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.admin.views.decorators import staff_member_required
from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseRedirect

#Import personales
from .decorators import anonymous_required
from .forms import SignUpForm

#Vistas
@anonymous_required
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            #Elementos del Perfil
            user.profile.nombre = form.cleaned_data.get('nombre')
            user.profile.apellido = form.cleaned_data.get('apellido')
            user.profile.localidad = form.cleaned_data.get('localidad')
            user.profile.telefono = form.cleaned_data.get('telefono')
            user.profile.empresa = form.cleaned_data.get('empresa')
            user.profile.producto = form.cleaned_data.get('producto')
            #Guardamos el usuario
            user.is_active = False
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            login(request, user)
            return render(request, 'registrado.html',)
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

@staff_member_required
def administracion(request):
    return render(request, 'administracion.html',)

@staff_member_required
def mostrar_usuarios(request):
    usuarios = User.objects.all()
    return render(request, 'listado_usuarios.html', {'usuarios': usuarios,})

@staff_member_required
def activar_usuario(request, user_id):
    usuario = User.objects.get(id=user_id)
    usuario.is_active = True
    usuario.save()
    #Enviar Correo
    email = EmailMessage('Su cuenta de Marca Jujuy a sido Activada.',
                       'Bienvenido!', to=[usuario.email])
    email.send()
    return render(request, 'activado.html', {'usuario' : usuario})

@staff_member_required
def desactivar_usuario(request, user_id):
    usuario = User.objects.get(id=user_id)
    usuario.is_active = False
    usuario.save()
    return render(request, 'desactivado.html')

marcajujuy/registro/templates/activado.html
{% extends 'base.html' %}

{% block content %}
    <h3>El usuario {{ usuario.username }} a sido Activado con exito!</h3>
    <p>Recibira un correo en {{ usuario.email }} informandole de tal accion.</p>

    <a href="/usuarios">Regresar</a>
{% endblock %}

marcajujuy/registro/templates/administracion.html
{% extends 'base.html' %}

{% block content %}
    <h1>Links Disponibles</h1>
    <p>Acceda al listado de usuarios <a href="/usuarios/">Aqui</a></p>
    <p>Acceda al panel de Consultas <a href="/consultas/">Aqui</a></p>
    <p>Acceda a la Administracion Avanzada <a href="/admin/">Aqui</a></p>
{% endblock %}

marcajujuy/registro/templates/desactivado.html
{% extends 'base.html' %}

{% block content %}
  <h3>El usuario {{ user.username }} a sido Desactivado con exito!</h3>
  <a href="/usuarios">Regresar</a>
{% endblock %}

marcajujuy/registro/templates/listado_usuarios.html
{% extends 'base.html' %}

{% block content %}
  <ul>
    {% for usuario in usuarios %}
      <li>
          {{ usuario.username }}
          <br>{{ usuario.profile.nombre }} {{ usuario.profile.apellido }}
          <br>{{ usuario.email }}
          <br>{{ usuario.profile.localidad }}
          <br>{{ usuario.profile.empresa }}
          <br>{{ usuario.profile.producto }}
        <br>Estado: {{ usuario.is_active }}
        {% if not usuario.is_active %}
          <a href="/activar/{{ usuario.id }}">(ACTIVAR)
        {% elif not usuario.is_staff %}
          <a href="/desactivar/{{ usuario.id }}">(DESACTIVAR)
        {% endif %}</a>
      </li>

    {% endfor %}
  </ul>

{% endblock %}

marcajujuy/registro/templates/login.html
{% extends 'base.html' %}

{% block content %}
<section class="login">
  
  
  <div class="login-overlay-ignore">
    <div class="login-container">
    <h2>Ingrese a Marca Jujuy</h2>
    {% if form.errors %}
      <p style="color: red">Tu usuario y Contraseña son incorrectos, por favor intenta de nuevo.</p>
    {% endif %}
      <form method="post">
        {% csrf_token %}
          <div class="input-group">
            <label for="id_username">Usuario:</label><br>
            <input type="text" class="form-control" name="username" autofocus maxlength="254" required id="id_username" /><br>
          </div>
        
          <div class="input-group">
            <label for="id_password">Contraseña:</label><br>
            <input type="password" class="form-control" name="password" id="id_password" required /><br>
          </div>
        
          <div class="input-group">
          <button type="submit">Ingresar</button>
          </div>
          <a href="/signup/" class="signup">Eres nuevo? Registrate</a>
      </form>
    </div>
  </div>
  <div class="login-overlay"></div>
</section>
{% endblock %}

marcajujuy/registro/templates/registrado.html
{% extends 'base.html' %}

{% block content %}
<section class="login">
  <div class="login-overlay-ignore">
    <div class="login-container">
    <h3>Su registro fue procesado con exito!</h3>
      <p style="color: red">Se te informara por correo electronico cuando tu usuario sea activado.</p>
    </div>
  </div>
  <div class="login-overlay"></div>
</section>
{% endblock %}

marcajujuy/registro/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<section class="seccion-registro pagina-registro">
  <h2>Registro</h2>
  <hr>
  <form method="post">
    {% csrf_token %}
    <div class="input-group">
        <label for="id_username">Usuario:</label><br>
        <input type="text" class="form-control" name="username" autofocus maxlength="150" required id="id_username" />
    </div>
    
      <div class="input-group">
        <label for="id_email">Correo Electronico:</label><br>
        <input type="email" class="form-control" name="email" id="id_email" maxlength="254" />
        <small style="color: #eee; text-align: center;">A través de este correo se le informara que su cuenta fue aprobada.</small>
      </div>
    
      <div class="input-group">
        <label for="id_password1">Contraseña:</label><br>
        <input type="password" class="form-control" name="password1" id="id_password1" required />
      </div>
    
      <div class="input-group">
        <label for="id_password2">Repetir Contraseña:</label><br>
        <input type="password" class="form-control" name="password2" id="id_password2" required />
      </div>
    
      <div class="input-group">
        <label for="id_nombre">Nombre:</label><br>
        <input type="text" class="form-control" name="nombre" id="id_nombre" maxlength="50" required />
      </div>
    
      <div class="input-group">
        <label for="id_apellido">Apellido:</label><br>
        <input type="text" class="form-control" name="apellido" id="id_apellido" maxlength="50" required />
      </div>
    
      <div class="input-group">
        <label for="id_localidad">Localidad:</label><br>
        <input type="text" class="form-control" name="localidad" id="id_localidad" maxlength="30" required />
      </div>
    
      <div class="input-group">
        <label for="id_telefono">Telefono:</label><br>
        <input type="text" class="form-control" name="telefono" id="id_telefono" maxlength="20" required />
      </div>
    
      <div class="input-group">
        <label for="id_empresa">Empresa:</label><br>
        <input type="text" class="form-control" name="empresa" id="id_empresa" maxlength="100" required />
      </div>
    
      <div class="input-group">
        <label for="id_producto">Producto:</label><br>
        <textarea name="producto" class="form-control" id="id_producto" rows="10" cols="40" required></textarea>
      </div>
    <button type="submit">Registrarse</button>
  </form>
  </section>
{% endblock %}